### PR TITLE
Stay consistant with constructor without arguments

### PR DESCRIPTION
**Pull request by lucasmichot**
Stay consistant with constructor without arguments

### CODE REVIEW

**Comment by tymondesigns** [comment]
I really need to fix these tests randomly failing because of timings

**Comment by lucasmichot** [comment]
@tymondesigns you should use `Carbon` with setTestNow
I could solve these kind of issues with that

**Comment by tymondesigns** [comment]
Yea I've been thinking about doing it for a while.. but not got round to it

**Comment by tymondesigns** [comment]
it always seemed like it would be a pain to do.. probably not the case though

**Comment by lucasmichot** [comment]
I'll have a try. Anyway I still have to make a heavy use of this package for the next days.
If i can solve that, I'll submit a PR

**Comment by tymondesigns** [comment]
Cool, appreciate it

**Comment by lucasmichot** [comment]
Good night ;-)

**Pull request merged**
