### PR TITLE
A test coverage that just works fine

### PR DESCRIPTION
**Pull request by lucasmichot**
Scrutinizer-CI seems to have issue for test coverage even with an insanely long timeout.

https://codecov.io/ is free for public projects and its Chrome extension integrates with Github: https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf

### CODE REVIEW

**Comment by tymondesigns** [comment]
Yea Scrutinizer has been annoying me lately tbh, So I'm willing to give this a try

But doesn't this require:
```
after_success:
  - codecov`
```
?

**Comment by lucasmichot** [comment]
Good catch @tymondesigns : https://github.com/tymondesigns/jwt-auth/commit/798a37aa6b1763e81ce87047a1d20752163f626a

**Comment by lucasmichot** [comment]
Nevertheless, to really test this PR correctly might be work to re-run all tests with codecov enabled

**Comment by tymondesigns** [comment]
gonna have a play around now

**Comment by lucasmichot** [comment]
Feel free to close and reopen https://github.com/tymondesigns/jwt-auth/pull/431

**Pull request merged**
