### PR TITLE
Abstract Provider

### PR DESCRIPTION
**Pull request by lucasmichot**
As only the boot methods differ, the service providers can be abstracted.

---

https://styleci.io/analyses/qord5g can be auto-applied after merge.

### CODE REVIEW

**Comment by lucasmichot** [comment]
Ping @GrahamCampbell : https://styleci.io/analyses/8ADgBG
It seems strange that a final dot is added in this case.
`* {@inheritdoc }` => `* {@inheritdoc}.`

**Comment by tymondesigns** [comment]
I'll merge this in, just need to add the exception to the phpunit config

**Comment by tymondesigns** [comment]
I'll also remove those additions of the periods

**Comment by lucasmichot** [comment]
:+1:

**Comment by tymondesigns** [comment]
Looks like Graham quietly fixed this :smile: https://styleci.io/analyses/XNAJjE

**Pull request merged**
