### PR TITLE
Delete .php_cs

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This is unneeded because StyleCI does everything. This file is just more crap to maintain and run on the local system.

### CODE REVIEW

**Comment by tymondesigns** [comment]
Yea I guess that point was just proven by 2f6e65b18ad54e815ba7eef79bfdaf72c426dbc7. Forgot to update `.php_cs` to match.

Screw it, let's do this

**Comment by tymondesigns** [comment]
sorry @lucasmichot  😆

**Comment by lucasmichot** [comment]
I disagree, if i’m pushing 3 commits and that none of this commit respect styleci coding standards (which the PR author has strictly no clue of), you find yourself with 3 more commits of style fix.
It's bit like avoiding to run phpunit locally and checks it it passes on travis...
if style.yml file does not change everyday, why would .php_cs?

Graham and I "fight" for PRs for some years now (and we can sometimes be a bit "dry" with our arguments), and I am not denying the value of Styleci, neither the great work that @GrahamCampbell has done with it. I think this is a great and promising tool

I just feel like letting the submitter without any way to fix his code locally is not the best thing to do;
better a not completely sync php-cs file +  Styleci fix things, than nothing
Cf. laravel/framework

Just my late and sleepy opinion ;-) 

On 30 January 2016 at 00:16:26, Sean Tymon (notifications@github.com) wrote:

sorry @lucasmichot 😆

**Comment by GrahamCampbell** [comment]
StyleCI's purpose is to eradicate local dev tools and IDEs. :trollface:

I say that with more seriousness than you might think though, lol. I don't use any local dev tools and IDEs, and work faster like that.

**Comment by GrahamCampbell** [comment]
But seriously, having StyleCI and TravisCI setup for CI services, and having a staging environment(s) to test on, you really don't need anything installed on your local machine, in fact, that's actually how I do StyleCI development.

**Comment by lucasmichot** [comment]
Too sleepy for more arguments (that you can be sure @GrahamCampbell, I got)  ;-)

doctor-evil-quote_56abfa69ce5152467

**Comment by GrahamCampbell** [comment]
lol

**Comment by GrahamCampbell** [comment]
I still think "push and forget" makes more sense than "download a load of tools, work out how to use them, configure them, keep them up-to-date, remember to actually run them". :P

**Comment by lucasmichot** [comment]
Make sense in some ways... ;-)

**Comment by tymondesigns** [comment]
I think there a valid points on both sides here. I'll see how things go..

**Comment by GrahamCampbell** [comment]
You'll get the most out of StyleCI if you enable auto sending and merging in https://styleci.io/repos/23680678/settings.

**Comment by tymondesigns** [comment]
@GrahamCampbell I assume a PR wont be created until the proposed PR is merged in?

**Comment by GrahamCampbell** [comment]
StyleCI creates fix PRs for commits pushed to the codebase only. It won't create them for external PRs.

**Comment by tymondesigns** [comment]
Makes sense, thanks

**Pull request merged**
