### PR TITLE
Only calculate default values when this is required

### PR DESCRIPTION
**Pull request by lucasmichot**
Only calculate default values when this is required

### CODE REVIEW

**Comment by tymondesigns** [comment]
curious.. what's the rationale for this?

**Comment by tymondesigns** [comment]
just given that this is the code that runs:

```php
public function get($key, $default = null)
{
    return array_key_exists($key, $this->parameters) ? $this->parameters[$key] : $default;
}
```

I guess a very slight perf increase?

**Comment by lucasmichot** [comment]
The fact is that we calculate the default in all cases.
Using ?: avoids that

**Comment by tymondesigns** [comment]
I see your point :+1:

**Pull request merged**
