### PR TITLE
Blacklisted tokens can be refreshed

### PR DESCRIPTION
**Pull request by BasConijn**
The blacklist is checked before refreshing the token.

### CODE REVIEW

**Comment by tymondesigns** [comment]
If a token is blacklisted then it should not be refreshable, otherwise there's no point in having a blacklist.

Or am I missing something?

**Comment by BasConijn** [comment]
Yeah, that is exactly the problem.
An blacklisted token can be refreshed.
The pull request fixes that.

**Comment by BasConijn** [comment]
I want to write an test to prove that an blacklisted token can be refreshed.
However I am running against an issue with mockery.
I have added this to the ManagerTest.php

`    /**
     * @test
     * @expectedException \Tymon\JWTAuth\Exceptions\TokenBlacklistedException
     */
    public function it_should_not_refresh_a_blacklisted_token()
    {
        $claims = [
            new Subject(1),
            new Issuer('http://example.com'),
            new Expiration($this->testNowTimestamp - 3600),
            new NotBefore($this->testNowTimestamp),
            new IssuedAt($this->testNowTimestamp),
            new JwtId('foo'),
        ];
        $collection = Collection::make($claims);

        $this->validator->shouldReceive('setRefreshFlow->check')->andReturn($collection);
        $payload = new Payload($collection, $this->validator);
        $token = new Token('foo.bar.baz');

        // Depending on the place in the code and parameters, this will or won't throw the exception
        $this->jwt->shouldReceive('decode')->with('foo.bar.baz')->andReturn($payload->toArray()); // ->andThrow(new TokenBlacklistedException());

        $this->factory->shouldReceive('setRefreshFlow')->with(true)->andReturn($this->factory);

        $this->blacklist->shouldReceive('has')->with($payload)->andReturn(true);

        $this->manager->refresh($token);
    }
`

**Comment by tymondesigns** [comment]
This should now be resolved as per #1062

**Pull request closed without merging**
