### PR TITLE
Upgrade to support Doctrine entities

### PR DESCRIPTION
**Pull request by oscaragcp**
Doctrine entitiy attributes are not usually public, so it is necessary to access them by a method instead of directly. I have made a small fix to support this without having to change anything else.

### CODE REVIEW

**Comment by tymondesigns** [comment]
Thanks for this... but the next version will take a different approach (check out the develop branch if you like)

**Comment by oscaragcp** [comment]
I will check the develop branch.

Thanks.

2015-05-20 22:54 GMT+01:00 Sean Tymon <notifications@github.com>:

> Thanks for this... but the next version will take a different approach
> (check out the develop branch if you like)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/pull/116#issuecomment-104049820>
> .
>



-- 
Óscar Antonio González de Chaves Pérez
oscar.agcp@gmail.com

+34 618 723 835

**Comment by oscaragcp** [comment]
Hi Sean,

I have updated to develop branch. I am facing an issue, I get this error
message:

{"error":{"message":"Could not create token: Undefined index:
alg","status_code":500}}

Digging in the code, I found this line in file
vendor/namshi/jose/src/Namshi/JOSE/JWS.php:

Line (182): $signerClass =
sprintf("Namshi\\JOSE\\Signer\\$this->encryptionEngine\\%s",
$this->header['alg']);

However, at this point $this->header['alg'] does not exist, headers array
only contains: "typ" => "JWT".

Is this a bug or I am missing anything?

Regards,

2015-05-21 7:33 GMT+01:00 Óscar Antonio González de Chaves Pérez <
oscar.agcp@gmail.com>:

> I will check the develop branch.
>
> Thanks.
>
> 2015-05-20 22:54 GMT+01:00 Sean Tymon <notifications@github.com>:
>
>> Thanks for this... but the next version will take a different approach
>> (check out the develop branch if you like)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tymondesigns/jwt-auth/pull/116#issuecomment-104049820>
>> .
>>
>
>
>
> --
> Óscar Antonio González de Chaves Pérez
> oscar.agcp@gmail.com
>
> +34 618 723 835
>



-- 
Óscar Antonio González de Chaves Pérez
oscar.agcp@gmail.com

+34 618 723 835

**Comment by tymondesigns** [comment]
Fixed in a recent commit. Please run composer update

**Comment by oscaragcp** [comment]
Thank you very much, I will try it.


2015-06-11 10:07 GMT+01:00 Sean Tymon <notifications@github.com>:

> Fixed in a recent commit. Please run composer update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/pull/116#issuecomment-111052370>
> .
>



-- 
Óscar Antonio González de Chaves Pérez
oscar.agcp@gmail.com

+34 618 723 835

**Pull request closed without merging**
