### PR TITLE
status code on error should be 401

### PR DESCRIPTION
**Pull request by jdsingh**
fixes issue #117

### CODE REVIEW

**Comment by codeorganic** [comment]
User Not Found should be 404 @jdsingh 

This pull request should be rejected

**Comment by jdsingh** [comment]
@codeorganic Purpose of this middleware is to find the user by auth token and log user into the app. 

If the user account does not exists that makes the Request invalid and code 404 should be user where the request is valid but the resource requested does not exist.

Check definition of [404](http://httpstatus.es/404)  it says "Subsequent requests by the client are permissible." but in this case they are not.

**Comment by tymondesigns** [comment]
I have now deleted the `laravel-5` branch, I will add this in myself, unless you want to recreate it targetting `develop`

**Comment by Mr-Anonymous** [comment]
Is this fixed? I installed it on Laravel 5.1 and I noticed the same. For token expired errors, the auth middleware actually returns `{"error":"token_not_provided"}` with a 400 status. Due to which the http interceptor are not triggered.

**Pull request closed without merging**
