### PR TITLE
Add isPast and isFuture helpers

### PR DESCRIPTION
**Pull request by lucasmichot**
Add `isPast` and `isFuture` helpers.

### CODE REVIEW

**Comment by tymondesigns** [comment]
@lucasmichot would you mind resolving the conflicts added by #572 ?

**Comment by lucasmichot** [comment]
Done with https://github.com/lucasmichot/jwt-auth/commit/f862d70638a1225b5ad745a021b45dae0eacc261 @tymondesigns

**Comment by lucasmichot** [comment]
See https://github.com/tymondesigns/jwt-auth/commit/cca8d07e3143a416e0f5823fdf874049c127e02a @tymondesigns

**Comment by tymondesigns** [comment]
Nice 1 :+1:

**Pull request merged**
