### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by mfn**
## Summary
- Add support for Laravel 8
- Test on PHP 7.4
- Remove testing on hhvm (doesn't work)

### CODE REVIEW

**Comment by mfn** [comment]
Travis not running? 🤔

**Comment by mfn** [comment]
> Travis not running? 🤔

Ah, it is => https://travis-ci.org/github/tymondesigns/jwt-auth/builds/723243303

But the travis <> github connection seems to be broken

**Comment by mfn** [comment]
All green! (except hhvm 🗑️ )

image

**Comment by mfn** [comment]
All tests green https://travis-ci.org/github/tymondesigns/jwt-auth/builds/723255098
image

**Review by StoneyEagle — APPROVED** [review]

**Review by countnoobula — APPROVED** [review]
Can we merge this please, I have an upgrade pending this package.

**Comment by sergiy-petrov** [comment]
@tymondesigns any chance to support laravel 8?

**Comment by tymondesigns** [comment]
Thanks @mfn :+1:

**Pull request merged**
