### PR TITLE
Replace CRLF with PHP_EOL

### PR DESCRIPTION
**Pull request by KarboniteKream**
Uses correct line endings on the target platform.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Should be platform independent.

**Comment by KarboniteKream** [comment]
What do you mean? It was using `\r\n` before.

**Comment by tymondesigns** [comment]
Yea so `PHP_EOL` is platform agnostic, I think @GrahamCampbell may have misread the diff ?

**Comment by GrahamCampbell** [comment]
No, I didn't missread this. PHP_EOL was not intended for that use.

**Comment by GrahamCampbell** [comment]
> Yea PHP_EOL is platform agnostic,

No it's not. The whole point of it is that it's the exact opposite. It changes per OS. We have no need for that.

**Comment by GrahamCampbell** [comment]
TBH, I'm actually just recommend changing it to use only the unix style, as is the PSR standard.

**Comment by tymondesigns** [comment]
> TBH, I'm actually just recommend changing it to use only the unix style, as is the PSR standard.

OK are you referring to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#22-files) here?

**Comment by tymondesigns** [comment]
Also PHP_EOL will out put the correct output if on a *nix OS anyway right.. so does it matter?

**Comment by GrahamCampbell** [comment]
But it'll output windows style on windows. Being on windows doesn't mean you have to use the windows style newlines. I don't.

**Pull request merged**
