### PR TITLE
Fixed position of getting the response before blacklisting

### LINKED ISSUE #808: RefreshToken is prematurely blacklisted
When using the 1.0.0-alpha.2 version of the RefreshToken with the "jwt.refresh" the token is first refreshed and then it is being checked for the next request. This result in the current token being blacklisted by the refresh() call and not proceeding to execute the request. 

```
public function handle($request, Closure $next)
    {
        $this->checkForToken($request);

        try {
            $token = $this->auth->parseToken()->refresh();
        } catch (JWTException $e) {
            throw new UnauthorizedHttpException('jwt-auth', $e->getMessage(), $e, $e->getCode());
        }

        $response = $next($request);

        // send the refreshed token back to the client
        $response->headers->set('Authorization', 'Bearer '.$token);

        return $response;
    }
```

should be:

```
public function handle($request, Closure $next)
    {
        $this->checkForToken($request);

        $response = $next($request);

        try {
            $token = $this->auth->parseToken()->refresh();
        } catch (JWTException $e) {
            throw new UnauthorizedHttpException('jwt-auth', $e->getMessage(), $e, $e->getCode());
        }

        // send the refreshed token back to the client
        $response->headers->set('Authorization', 'Bearer '.$token);

        return $response;
    }
```

### PR DESCRIPTION
**Pull request by bkolicoski**
This fixes #808

### CODE REVIEW

**Comment by lucasmichot** [comment]
Can you fix your style @bkolicoski ?

**Comment by feeekkk** [comment]
but can't this allow an unauthorized request to process before an exception is thrown?

**Comment by tdhsmith** [comment]
@feeekkk Yeah. I brought that up in #808.

**Comment by bkolicoski** [comment]
@lucasmichot Sorry about that. I fixed it now.

**Comment by tymondesigns** [comment]
#1062 should have resolved this

**Pull request closed without merging**
