### PR TITLE
Use the same styleci definition on master as the one used on develop

### PR DESCRIPTION
**Pull request by lucasmichot**
And avoid merging conflicts

### CODE REVIEW

**Comment by lucasmichot** [comment]
Indeed : https://styleci.io/analyses/864nko

**Comment by GrahamCampbell** [comment]
All this has done is cause conficts.

**Comment by tymondesigns** [comment]
I doubt I will be doing a normal merge from dev -> master tbh... 

The changes are vast at this point, and no need to go through that pain

**Comment by lucasmichot** [comment]
@GrahamCampbell teh branches are already not synced, as some PR, see https://github.com/tymondesigns/jwt-auth/pull/446 for instance

**Pull request merged**
