### PR TITLE
Add support for Laravel 5.2

### PR DESCRIPTION
**Pull request by crynobone**
* Add support for Laravel 5.1 and Laravel 5.2
* Update travis-ci to include test on both setup.

~~There one failing on laravel 5.1 test at the moment. I not sure how that would relate with the changes.~~

### CODE REVIEW

**Comment by tymondesigns** [comment]
Thanks for this, why is `paragonie/random_compat` required ?

**Comment by crynobone** [comment]
@tymondesigns 

Because `Str::random()` now utilize `random_byte()` which is PHP7 feature, `paragonie/random_compact` provides the polyfill for the function.

https://github.com/illuminate/support/blob/5.2/Str.php#L233

**Comment by crynobone** [comment]
screen shot 2015-12-18 at 7 26 50 pm

This would be the output if I remove `paragonie/random_compat` deps and set `"prefer-stable": false,` with this changes.

**Comment by irazasyed** [comment]
+1 was having issue today when working with Laravel 5.2.

**Comment by Fed03** [comment]
:+1:

**Comment by jonagoldman** [comment]
+1 Specially now that 5.2 is officially released.

**Comment by LukasMa** [comment]
:+1:  Need this merged :)

**Comment by tymondesigns** [comment]
@crynobone I have changed `Str::random()` to `Str::quickRandom()` so shouldn't need to pull in `paragonie/random_compat` anymore. 

Could you remove that & I will merge this in :+1:

**Comment by tdhsmith** [comment]
Looks good for compatibility, though I think a future Laravel 5.2 "embracing" release would use the new authentication driver system, which seems to have been designed specifically for this package's use-case. [The documentation on it even uses JWTs as an example!](https://laravel.com/docs/5.2/authentication#adding-custom-guards)

**Comment by tymondesigns** [comment]
@tdhsmith yes you are bang on there.. I only caught wind of the Auth changes via listening to the podcast - http://www.laravelpodcast.com/episodes/22314-episode-39-updates-on-all-the-things

But ultimately, we will need a release after this one that hooks into the new Auth guards properly.

Also, great to see that example in the docs! :smile:

**Comment by tymondesigns** [comment]
Actually I'll just get this merged now and remove the ref myself Thanks

**Comment by andrewmclagan** [comment]
Any timeline for native 5.2 auth driver support? Would be more then happy to do a PR if one is not already in build...

**Pull request merged**
