### PR TITLE
Fixes ResponseFactory not being instantiable building BaseMiddleware

### PR DESCRIPTION
**Pull request by GiampaoloFalqui**
Fixes [Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable while building [...]](https://github.com/laravel/framework/issues/12368#issuecomment-185792630)

### CODE REVIEW

**Comment by dlucian** [comment]
I'm having the same issue after `composer update`. When we can have this merged into `master`?

**Comment by GiampaoloFalqui** [comment]
It seems like today reverting this workaround fix, the library works again. Maybe something Illuminate's team forgot to add? I don't know. I'll close this since it's not needed anymore.

**Comment by GiampaoloFalqui** [comment]
This is a workaround without touching the library to fix this issue (Lumen only, I think).

Add in your AppServiceProvider these three lines of code:
```php
$this->app->singleton('Illuminate\Contracts\Routing\ResponseFactory', function ($app)
{
    return new ResponseFactory($app['Illuminate\Contracts\View\Factory'], $app['Illuminate\Routing\Redirector']);
});
```

**Comment by dlucian** [comment]
@GiampaoloFalqui Thanks for the fix, it's working great! 
I was already started worrying on how to deploy this with the library changes.

**Comment by tymondesigns** [comment]
So this is a bug within Lumen then? If there is a workaround then I'll close this.

**Comment by dlucian** [comment]
@tymondesigns Yeah, but might be worth mentioning this in the Installation instructions. Otherwise some people are going to go through some rough times :)

**Comment by hopewise** [comment]
I have the same issue here, I am on lemon, but the above solution didn't work..

**Comment by ihsanberahim** [comment]
@GiampaoloFalqui TQ! It works!

**Pull request closed without merging**
