### PR TITLE
Refactor the command.

### PR DESCRIPTION
**Pull request by lucasmichot**
Refactor the command.

### CODE REVIEW

**Comment by tymondesigns** [comment]
Cheers.. might have another go at adding tests for this

**Comment by lucasmichot** [comment]
Yep would make sense !

**Comment by lucasmichot** [comment]
In fact, after having thought a bit about it - I think I would just remove this command as this is obvious that a token needs to be set.

I would only raise an exception when the size of the token is < 32 characters.

**Comment by tymondesigns** [comment]
@lucasmichot That's a fair point.. I'll have a think about it

**Pull request merged**
