### PR TITLE
More tests fixes

### PR DESCRIPTION
**Pull request by lucasmichot**
Some more test fixes
And add AbstractMiddlewareTest

### CODE REVIEW

**Comment by tymondesigns** [comment]
👍

**Comment by lucasmichot** [comment]
Looks like a stable release soon :-)

**Comment by tymondesigns** [comment]
Yes it does!

**Comment by tymondesigns** [comment]
Already planning 1.1 release.. dropping laravel 5.1 and removing all the auth stuff that isn't guard related.

Also considering php 7 only.. what do you think?

**Comment by lucasmichot** [comment]
I would go for droping not guard related stuff 

But forcin php>=7 would lock force to L>=5.5
Any specific reason for that ?

**Comment by tymondesigns** [comment]
None other than, because I want to play around more with some of the newer features. Type hint all the things etc 😀

But I think I should be a little bit responsible and resist the temptation.. could be a shit storm of php 5.* Peeps

**Comment by lucasmichot** [comment]
Ah ah ah !
As long as previous version plays nice with PHP=<7.0 and L=<5.5, I believe you can make it

**Comment by lucasmichot** [comment]
Tough choice

**Comment by tymondesigns** [comment]
I'll see how things play out, once 1.0.0 is out the door

**Pull request merged**
