### PR TITLE
Get rid off Codecov

### PR DESCRIPTION
**Pull request by lucasmichot**
- Get rid off Codecov
- Get rid off coverage within TravisCI

---

Codecov service shall also be disabled

### CODE REVIEW

**Comment by lucasmichot** [comment]
(codecov service shall also be disabled)

**Comment by tymondesigns** [comment]
why get rid of codecov?

**Comment by lucasmichot** [comment]
Totally messed up with this PR, and send it to the wrong project
NVM ;-)

**Comment by tymondesigns** [comment]
Ah okidoke ;)

**Pull request closed without merging**
