### PR TITLE
Add and tests Illuminate 5.5.

### PR DESCRIPTION
**Pull request by lucasmichot**
Add and tests Illuminate 5.5.

---

@tymondesigns - this should re-tested and merged **ONLY** after 5.5 release

### CODE REVIEW

**Comment by josephtaylor-mn** [comment]
Any idea when you might this is coming down the pipe?

**Comment by tymondesigns** [comment]
@lucasmichot Have any thoughts on that failure?.. seems to be related to a commit of yours on `illuminate/contracts` https://github.com/illuminate/contracts/commit/7e5932b97a04ef8323a0f49b2430aa39142c812c

**Comment by tymondesigns** [comment]
🎉 💥  Cheers!!

**Comment by kohenkatz** [comment]
@tymondesigns Less than 8 hours after the 5.5 release - wow, that was fast!

Just to keep things clean, can you close #1271 and #1289?

**Comment by cboisen** [comment]
So I'm curious - how do I get to test this out in my own installation?

**Pull request merged**
