### PR TITLE
TokenParser should take into account route parameters

### PR DESCRIPTION
**Pull request by andrzejkupczyk**
… because parsing headers and GET parameters is not enough :smirk:

### CODE REVIEW

**Comment by tymondesigns** [comment]
Thanks!

**Comment by crynobone** [comment]
Was this tested with Lumen?

```
{
  "message": "Call to a member function parameter() on array",
  "code": 1,
  "status_code": 500,
  "debug": {
    "line": 87,
    "file": "/home/vagrant/katsana/vendor/tymon/jwt-auth/src/Http/TokenParser.php",
    "class": "Symfony\Component\Debug\Exception\FatalErrorException",
    "trace": [
      "#0 /home/vagrant/katsana/vendor/orchestra/lumen/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\Lumen\Application->handleShutdown()",
      "#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()",
      "#2 {main}"
    ]
  }
}
```

**Comment by andrzejkupczyk** [comment]
I didn't have enough time to get this package working with Lumen however route resolver shouldn't return array according to [this](https://github.com/illuminate/http/blob/master/Request.php#L796).
Did you run phpspec (`it_should_return_the_token_from_route` example)?
Did you try #363 fix?

**Comment by crynobone** [comment]
Both solutions doesn't work on Lumen 5.2.

**Comment by andrzejkupczyk** [comment]
There is no Lumen 5.2 release, nice try :wink: 
It seems that your problem is related to JWT-AUTH middleware or [framework itself](https://github.com/laravel/lumen-framework/issues/291). Dunno. As I said, route resolver shouldn't return an array and this is your case.

**Comment by crynobone** [comment]
https://github.com/laravel/lumen-framework/blob/master/composer.json

So meaning jwt-auth doesn't need to prepare for the upcoming release (which going to be release soon). Good job guys!

**Comment by crynobone** [comment]
What phpspec? This project only loads illuminate components, it not testing against full Laravel or Lumen integration. And tested only with phpunit.

**Comment by tymondesigns** [comment]
@crynobone Don't worry, I will be testing everything thoroughly with both Laravel and Lumen prior to the final `0.6` release.

This is still the develop branch afterall :smile:

**Comment by tymondesigns** [comment]
This issue may well be related to https://github.com/laravel/lumen-framework/issues/291.

But I haven't checked that through myself yet.

**Pull request merged**
